#ifndef _SKETCHES_VERSION_H_
#define _SKETCHES_VERSION_H_

#ifndef SKETCHES_VERSION_MAJOR
#define SKETCHES_VERSION_MAJOR (1)
#endif

#ifndef SKETCHES_VERSION_MINOR
#define SKETCHES_VERSION_MINOR (1)
#endif

#define SKETCHES_MODULE_VERSION (SKETCHES_VERSION_MAJOR * 100 + SKETCHES_VERSION_MINOR)

#endif